# Generated by Django 4.1.7 on 2023-03-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
                ("password", models.CharField(max_length=255, null=True)),
            ],
            options={
                "verbose_name_plural": "TestModel",
            },
        ),
    ]
