# Generated by Django 4.1.7 on 2023-02-23 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('None', 'No Priority'), ('1', 'Important'), ('2', 'Urgent And Important')], default='None', max_length=20)),
                ('deadline', models.DateField()),
                ('favorites', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'TodoLists',
            },
        ),
        migrations.CreateModel(
            name='TodoTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('priority', models.CharField(choices=[('None', 'No Priority'), ('1', 'Important'), ('2', 'Urgent And Important')], default='None', max_length=20)),
                ('status', models.BooleanField(default=False)),
                ('favorite', models.BooleanField(default=False)),
                ('deadline', models.DateField()),
                ('list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todosApp.todolists')),
            ],
            options={
                'verbose_name_plural': 'TodoTasks',
            },
        ),
    ]
