# Generated by Django 4.1.7 on 2023-02-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todosApp', '0005_alter_todolists_deadline_alter_todotasks_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolists',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
