# Generated by Django 4.1.7 on 2023-02-24 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todosApp', '0006_todolists_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolists',
            name='count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='todotasks',
            name='list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='todosApp.todolists'),
        ),
    ]
