# Generated by Django 4.1.7 on 2023-02-24 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todosApp', '0007_alter_todolists_count_alter_todotasks_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolists',
            name='count',
        ),
    ]
